### PR TITLE
Proposing bundler to install mean stack from mean.io

### PR DESCRIPTION
**Pull request by P1xt**
Added installer/uninstaller for grunt and mean then created mean-io-stack entries which install/uninstall everything necessary for the mean stack: grunt, mongodb, and mean.

I didn't include install/uninstall of node and npm as they're pre-installed on a fresh VM and it seemed unwise to uninstall koding baseline installs.

TODO: Think some on a better way to keep track of what was installed via kpm install. Scenario: user installs mongodb either via kpm or command line then installs mean-io-stack (which will just skip the mongodb install if it finds mongodb already present), uninstall has no way to know that mongodb was installed stand-alone and not part of the stack install and will uninstall it as part of mean-io-stack uninstall.

### CODE REVIEW

**Comment by P1xt** [comment]
Will resend momentarily, but correct and less messy ;)

**Comment by leeola** [comment]
Hmm, i did some correction work on the Develop branch last night and it seems to have messed with your PR (as you can see by the merge conflicts). Can you either copy your files into a new branch & PR, or cherry pick them into a new PR?

If either of those are something confusing to you, let me know and i'll try pulling your branch and cherrypicking (i believe Github's Hub tool will let me do this) myself.

Your additions look great though! Can't get to get this merged :+1:

**Comment by P1xt** [comment]
Yep, I'll re-branch ... that does look odd.

**Comment by P1xt** [comment]
Will resend pull request as a branch,

**Pull request closed without merging**
